module Accept = Accept
module Auth = Auth
module Body = Body
module Conf = Conf
module Connection = Connection [@@deprecated "Connection.t values are useless."]
module Code = Code
module Cookie = Cookie
module Header = Header
module Link = Link
module Request = Request
module Response = Response
module S = S
module Path = Path
module Transfer = Transfer
