name: "Nix"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      NIXPKGS_ALLOW_INSECURE: 1
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix develop -c dune build @runtest @check
